### ISSUE TITLE
Can't startup project

### ISSUE THREAD

**Issue by n1kt0** [srinituraga/cnpkg#1]
Hi Srini,
I can't start up the project, first I edited the start up file because of a dependency of your local file system layout. Second the script tries to call an EMstartup  function which I can't find anywhere.

Would be nice if you could help out!

Best regards,

Nikita

**Comment by srinituraga** [comment]
Thanks for your interest.

But I'm afraid this repo isn't maintained any more. Please check out our awesome new gunpowder library! https://github.com/funkey/gunpowder

In any case, here's the EMstartup.m file.
```
set(0,'UserData',EMroot);

addpath([EMroot '/util'])
addpath([EMroot '/vis'])
addpath([EMroot '/segmentation'])
addpath([EMroot '/analysis'])
addpath([EMroot '/validate'])
addpath([EMroot '/parallel'])
addpath([EMroot '/nn/convnet'])
addpath([EMroot '/nn/hdf5'])

clear EMroot
```
